###
POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "My 2nd Blog",
    "author": "Jordan J",
    "url": "the url",
    "likes": 1
}

###
GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
content-type: application/json

{
    "author": "Jordan J",
    "likes": 1
}