###
POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYxYTE4YTI1ZDUyNDYyMjllZjZmOTk0NCIsImlhdCI6MTYzNzk3Nzk4NywiZXhwIjoxNjM3OTgxNTg3fQ.iMJqBi2_HwHrilHz3v4Zuzr-DuWFqz34vJjHpskwNlg

{
    "title": "Blog 4",
    "author": "Craft J",
    "url": "the url",
    "likes": 4
}

###
GET http://localhost:3003/api/users

###
POST http://localhost:3003/api/users
content-type: application/json

{
    "username": "root",
    "name": "superuser",
    "password": "password"
}

###
POST  http://localhost:3003/api/login
content-type: application/json

{
    "username": "testuser",
    "password": "testtest"
}

###
DELETE http://localhost:3003/api/blogs/61a19044304c6fd3969e0b92
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyIiwiaWQiOiI2MWExOGEwNmQ1MjQ2MjI5ZWY2Zjk5M2YiLCJpYXQiOjE2Mzc5NzkwOTIsImV4cCI6MTYzNzk4MjY5Mn0.QYo84egWO0Yv73yuCqnQXo9vGPSDq2BDh_atxAtXLiI